name: DeployToGitHubPages
env:
  PUBLISH_DIR: JsonKeyConvert/bin/Release/net7.0/publish/wwwroot
  # Include subfolders if needed

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish app
        run: bash publish.sh
        # You can use cd before if your project is in a subfolder
        
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /JsonKeyConvert/

      - name: GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}